### ISSUE TITLE
0.5.1 breaks some of my widget display

### ISSUE THREAD

**Issue by pashdown** [hassio-addons/app-appdaemon#101]
# Problem/Motivation

0.5.1 breaks some of my dashboard widget display

## Expected behavior

0.5.1 breaks a sensor display and two widgets temperature displays.  I tried moving the temperature widgets to the top row and they display, so something funky is going on.   This is what it should look like:

![image](https://user-images.githubusercontent.com/175150/113763785-539f0e80-96d7-11eb-9d3c-950372f43bf3.png)

## Actual behavior

This is what it looks like after going from 0.4.4 to 0.5.1:

![image](https://user-images.githubusercontent.com/175150/113763717-3c602100-96d7-11eb-9115-26a0b9aeed76.png)

## Steps to reproduce

Here are the dashboard widgets in question:
```
0_sales_temperature:
  widget_type: sensor
  title: "0 Sales Temperature"
  units: "&deg;F"
  precision: 0
  entity: sensor.0_sales_multisensor_air_temperature

0_techpit_temperature:
  widget_type: sensor
  title: "0 Techpit Temperature"
  units: "&deg;F"
  precision: 0
  entity: sensor.0_techpit_south_multisensor_air_temperature

dishwasher_last_washed:
  title: 'Dishwasher Last Washed'
  state_text: 1
  widget_type: icon
  entity: sensor.dishwasher_last_washed
  icons:
    "default":
      icon: mdi-dishwasher
      style: "color: cyan"
```
