### ISSUE TITLE
Camera widget fails with token=undefined

### ISSUE THREAD

**Issue by pashdown** [hassio-addons/app-appdaemon#148]
# Problem/Motivation

> Camera widget has stopped working.  Camera is functional on the HA Lovelace page.

## Expected behavior

> To see what the camera was formerly showing

## Actual behavior

> 401 error to the proxy, token=undefined

## Steps to reproduce

>
```yaml
camera_front_door:
  widget_type: camera
  entity: camera.front_door
  refresh: 0
  stream: 1
  base_url: http://192.168.0.10:8123
```
## Proposed changes

> I tried creating a longterm token and putting that in the config, although add-on advises against it.  It still comes out as token=undefined in the request.
