### ISSUE TITLE
Disconnected from home assistant how do I fix this issue?

### ISSUE THREAD

**Issue by SP-Mushrooms** [hassio-addons/app-appdaemon#197]
# Problem

> I followed [https://appdaemon.readthedocs.io/en/latest/CONFIGURE.html](url) for configuration but I keep on getting WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds in the logs

## Expected behavior

> The apps startup and I can use it

## Actual behavior

> keeps on giving the line WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds in the log

## Steps to reproduce

> I am using home assistant supervise I added the appdaemon into home assistant and added this into appdaemon yaml. What did I do wrong?
```
secrets: /config/secrets.yaml
appdaemon:
  time_zone: CET
  latitude: 51.725
  longitude: 14.3434
  elevation: 0
  plugins:
    HASS:
      type: hass
      ha_url: http://XXX.XXX.XXX.XXX:8123
      token: 
<token key>
      app_init_delay: 20
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:
logs:
  main_log:
    filename: /config/appdaemon/logs/appdaemon.log
  access_log:
    filename: /config/appdaemon/logs/access.log
  error_log:
    filename: /config/appdaemon/logs/error.log
  diag_log:
    filename: /config/appdaemon/logs/diag.log
    log_generations: 5
    log_size: 1024
    format: "{asctime} {levelname:<8} {appname:<10}: {message}"
  test_log:
    name: TestLog
    filename: /config/appdaemon/logs/test.log
```
![image](https://user-images.githubusercontent.com/96763450/171566288-82200ce2-fc00-46f5-8b30-12287dccad1b.png)
