### ISSUE TITLE
'log' directive deprecated

### ISSUE THREAD

**Issue by Mariusthvdb** [hassio-addons/app-appdaemon#2]
# Problem/Motivation
upgraded to the new add-on and all in the log is the below error about the log directive
> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)
```
[09:54:38] INFO: Starting AppDaemon...
ERROR 'log' directive deprecated, please convert to new 'logs' syntax
[09:54:40] INFO: Starting AppDaemon...
ERROR 'log' directive deprecated, please convert to new 'logs' syntax
[09:54:42] INFO: Starting AppDaemon...
ERROR 'log' directive deprecated, please convert to new 'logs' syntax
```
## Steps to reproduce

> (How can someone else make/see it happen)
config:
```
{
  "system_packages": [],
  "python_packages": [
    "geopy"
  ],
  "init_commands": []
}
```

system: Rpi4, Hassio 103.5
## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Please read the upgrade/migration instructions in the add-on manual.

**Comment by Mariusthvdb** [comment]
thanks Frenck, missed that, sorry..

**Comment by frenck** [comment]
No problem m8!

**Comment by Mariusthvdb** [comment]
just to be sure please let me check this quickly with you, we can use:
```
secrets: /config/secrets.yaml
appdaemon:
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  time_zone: !secret time_zone
```

(have to rule out possible reasons for my app which stopped working on AD4...)
