### ISSUE TITLE
ERROR MQTT: Unable to decode MQTT message

### ISSUE THREAD

**Issue by amaisano** [hassio-addons/app-appdaemon#275]
# Problem/Motivation

> Using ControllerX, my app settings for the IKEA Symfonisk dial no longer work. Each time I dial it the AppDaemon log is filled with these errors:

> 2023-09-24 18:12:34.999330 ERROR MQTT: Unable to decode MQTT message, with Traceback: Traceback (most recent call last): File "/usr/lib/python3.11/site-packages/appdaemon/plugins/mqtt/mqttplugin.py", line 271, in mqtt_on_message payload = payload.decode() ^^^^^^^^^^^^^^^^ UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

```yml
...
ikea_dial:
  module: controllerx
  class: E1744LightController
  controller: IKEA Dial
  constrain_input_boolean: input_boolean.pc_lights_on,on
  integration:
    name: z2m
    listen_to: mqtt
  light: light.pc
  merge_mapping:
    brightness_step_up:
      service: input_select.select_next
      data:
        entity_id: input_select.stage_lighting

ikea_dial_alt:
  module: controllerx
  class: E1744LightController
  controller: IKEA Dial
  constrain_input_boolean: input_boolean.pc_lights_on,off
  integration:
    name: z2m
    listen_to: mqtt
  light: light.office
  merge_mapping:
    toggle:
      service: light.toggle
      data:
        entity_id: light.pc
...
```

My other Z2M integration settings and actions work fine (I have several IKEA switches).

## Expected behavior

> Interacting with the E1744 should perform the HA actions configured in app.yaml. See https://xaviml.github.io/controllerx/controllers/E1744/?h=e1744#zigbee2mqtt-light

## Actual behavior

> Errors occur above. Other devices continue to work as configured.

## Steps to reproduce

> See above config and use E1744 hardware. Currently the device is on firmware `587683377` (not the most currently - have not been able to every update this device but it works fine before the most recent HA Update 2023.9.0).

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
