### ISSUE TITLE
"not a valid yaml file" when !including yaml files in apps.yaml

### ISSUE THREAD

**Issue by Biotronic** [hassio-addons/app-appdaemon#306]
I'm a bit confused now - I'm getting complaints that my !includes in apps.yaml are not valid yaml files.

An example:
```yaml
myclass:
  module: myclass
  class: MyClass
  api: !include /addon_configs/a0d7b954_appdaemon/apps/api.yaml
```

The `api` line gives this error message in the logs:

> ValueError: /addon_configs/a0d7b954_appdaemon/apps/api.yaml is not a valid yaml file

I've confirmed that's the right path. Are !includes not supposed to be in the /addon_configs folder? Should I move the apps.yaml (and/or other yaml files) back to the /config folder? Is this documented somewhere I haven't seen?

**Comment by frenck** [comment]
```yaml
myclass:
  module: myclass
  class: MyClass
  api: !include /config/apps/api.yaml
```

Inside add-ons the config folder is located in `/config`
