### ISSUE TITLE
Finally I got AppDaemon 15.2 running.

### ISSUE THREAD

**Issue by wdriessen** [hassio-addons/app-appdaemon#308]
After reverting my VM image again to a version containg AppDaemon 13.6, I updated ApDaemon to with the latest version (15.2). This time I only changed 
from: 
`secrets: /config/secrets.yaml`
to:
`secrets: /homeassistant/secrets.yaml`

The difference with my previous updates is that I emptied the log: references and app_dir: references, and this time AppDaemon started successfully. After open the "addon_configs" folder in visual studio code (via file-open folder) I can edit my python code again and everything is up and running. My working appdaemon.yaml file looks as follows:
```
http:
  url: http://127.0.0.1:5050
secrets: /homeassistant/secrets.yaml
logs:
appdaemon:
  # https://github.com/AppDaemon/appdaemon/issues/852
  # default 10 for both
  internal_function_timeout: 30
  thread_duration_warning_threshold: 20
  threads: 20
  production_mode: true
  app_dir: 
  latitude: 51.453647
  longitude: 6.063755
  elevation: 34
  time_zone: Europe/Amsterdam
  plugins:
    HASS:
      type: hass
api:
admin:
```
