### ISSUE TITLE
AppDaemon stopped working after the latest rapid succession updates, deployed 0.17.4 and it still doesn't work.

### ISSUE THREAD

**Issue by CitizenRacer** [hassio-addons/app-appdaemon#411]
I'm attaching my logs here. But this is what the logs look like:

`2025-06-04 09:36:49.432392 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2025-06-04 09:36:49.462805 INFO AppDaemon: Stopping apps from namespace 'default' because the plugin failed
2025-06-04 09:36:49.463104 INFO AppDaemon: Stopping apps: {'qolsys_panel'}
2025-06-04 09:36:49.463232 INFO AppDaemon: Calling terminate() for 'qolsys_panel'
2025-06-04 09:36:49.464986 INFO qolsys_panel: Terminating
2025-06-04 09:36:49.466791 INFO qolsys_panel: Terminated
2025-06-04 09:36:49.469071 INFO qolsys_panel: listening cancelled
2025-06-04 09:36:50.214931 WARNING HASS: ------------------------------------------------------------
2025-06-04 09:36:50.215403 WARNING HASS: Unexpected error during websocket send
2025-06-04 09:36:50.215733 WARNING HASS: ------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/appdaemon/utils.py", line 483, in wrapper
    result = await func(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/appdaemon/plugins/hass/hassplugin.py", line 369, in websocket_send_json
    await self.ws.send_json(request)
  File "/usr/lib/python3.12/site-packages/aiohttp/client_ws.py", line 261, in send_json
    await self.send_str(dumps(data), compress=compress)
  File "/usr/lib/python3.12/site-packages/aiohttp/client_ws.py", line 245, in send_str
    await self._writer.send_frame(
  File "/usr/lib/python3.12/site-packages/aiohttp/_websocket/writer.py", line 73, in send_frame
    raise ClientConnectionResetError("Cannot write to closing transport")
aiohttp.client_exceptions.ClientConnectionResetError: Cannot write to closing transport
2025-06-04 09:36:50.216011 WARNING HASS: ------------------------------------------------------------
2025-06-04 09:36:50.228436 INFO HASS: Previous message repeated 1 times
2025-06-04 09:36:50.228876 WARNING HASS: Unexpected error during websocket send
2025-06-04 09:36:50.229544 WARNING HASS: ------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/appdaemon/utils.py", line 483, in wrapper
    result = await func(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/appdaemon/plugins/hass/hassplugin.py", line 369, in websocket_send_json
    await self.ws.send_json(request)
  File "/usr/lib/python3.12/site-packages/aiohttp/client_ws.py", line 261, in send_json
    await self.send_str(dumps(data), compress=compress)
  File "/usr/lib/python3.12/site-packages/aiohttp/client_ws.py", line 245, in send_str
    await self._writer.send_frame(
  File "/usr/lib/python3.12/site-packages/aiohttp/_websocket/writer.py", line 73, in send_frame
    raise ClientConnectionResetError("Cannot write to closing transport")
aiohttp.client_exceptions.ClientConnectionResetError: Cannot write to closing transport`

[a0d7b954_appdaemon_2025-06-04T16-34-41.840Z.log](https://github.com/user-attachments/files/20595255/a0d7b954_appdaemon_2025-06-04T16-34-41.840Z.log)

Here's my appdaemon.yaml:

`secrets: /homeassistant/secrets.yaml
appdaemon:
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 2
  time_zone: America/Los_Angeles
  plugins:
    HASS:
      type: hass
      #ha_url: http://10.0.0.8:8123
      #token: !secret appdaemon_ha_token

      token: !env_var SUPERVISOR_TOKEN
    MQTT:
      type: mqtt
      namespace: mqtt
      client_host: !secret mqtt_host
      client_port: !secret mqtt_port
      client_user: AppDaemon
      client_password: VppP5v8cdlBrXU2
http:
  url: http://0.0.0.0:5050
admin:
api:
hadashboard:`

This is my apps.yaml
`
qolsys_panel:
  module: gateway
  class: QolsysGateway
  panel_host: !secret panel_host_ip
  panel_mac: !secret panel_mac_address
  panel_token: !secret panel_token
  panel_user_code: !secret alarm_panel_code
  code_arm_required: false
  code_disarm_required: false
  log_level: DEBUG

`

**Comment by SJLBoulder** [comment]
1) When the first of these appdaemon updates occurred a couple weeks ago, there was also a qolsysgw update. I found the qolsysgw update was installed in "/homeassistant/appdaemon/apps/qolsysgw".  So, I decided to relocate my "appdaemon/apps" directory to accomodate the qolsysgw install process and then also moved "apps.yaml" and "hello.py" to "/homeassistant/appdaemon/apps" AND, then added "app_dir: /homeassistant/appdaemon/apps" to the "appdaemon.yaml" file.

2) ALSO, there was a problem with the secrets. So, I also added "secrets: /homeassistant/secrets.yaml" to the "appdaemon.yaml" file.


Here are the file paths and file contents: 

PATH:  /addon_configs/aod7b954_appdaemon/appdaemon.yaml
CONTENT:
```
# appdaemon.yaml
secrets: /homeassistant/secrets.yaml
logs:
  main_log:
    filename: /homeassistant/appdaemon/logs/main.log
  error_log:
    filename: /homeassistant/appdaemon/logs/error.log
  diag_log:
    filename: /homeassistant/appdaemon/logs/diag.log
  access_log:
    filename: /homeassistant/appdaemon/logs/access.log
appdaemon:
  app_dir: /homeassistant/appdaemon/apps
  time_zone: !secret location_time_zone
  latitude: !secret location_latitude
  longitude: !secret location_longitude
  elevation: !secret location_elevation
  plugins:
    HASS:
      type: hass
      token: !env_var SUPERVISOR_TOKEN
    MQTT:
      type: mqtt
      namespace: mqtt # need same value in apps.yaml
      client_host: !secret appdaemon_mqtt_client_host
      client_port: !secret appdaemon_mqtt_client_port
      client_user: !secret appdaemon_mqtt_user
      client_password: !secret appdaemon_mqtt_password

http:
  url: http://0.0.0.0:5050
hadashboard:
admin:
api:
```


PATH: /homeassistant/appdaemon/apps/apps.yaml
CONTENT:
```
# apps.yaml

hello_world:
  module: hello
  class: HelloWorld

qolsys_panel:
  module: gateway
  class: QolsysGateway
  panel_unique_id: security
  panel_device_name: Security
  panel_user_code: !secret qolsys_panel_user_code
  panel_host: !secret qolsys_panel_host
  panel_token: !secret qolsys_panel_token
  panel_mac: !secret qolsys_panel_mac
```

**Comment by CitizenRacer** [comment]
Thanks for the data, I tried what you did...

/addon_configs/a0d7b954_appdaemon/appdaemon.yaml:
```
secrets: /homeassistant/secrets.yaml
appdaemon:
  app_dir: /homeassistant/appdaemon/apps
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 2
  time_zone: America/Los_Angeles
  plugins:
    HASS:
      type: hass
      token: !env_var SUPERVISOR_TOKEN
    MQTT:
      type: mqtt
      namespace: mqtt
      client_host: !secret mqtt_host
      client_port: !secret mqtt_port
      client_user: AppDaemon
      client_password: VppP5v8cdlBrXU2
http:
  url: http://0.0.0.0:5050
admin:
api:
hadashboard:
```

/homeassistant/appdaemon/apps/apps.yaml:
```

qolsys_panel:
  module: gateway
  class: QolsysGateway
  panel_host: !secret panel_host_ip
  panel_mac: !secret panel_mac_address
  panel_token: !secret panel_token
  panel_user_code: !secret alarm_panel_code
  code_arm_required: false
  code_disarm_required: false
  log_level: DEBUG
```

But I still get these errors

[a0d7b954_appdaemon_2025-06-04T22-58-44.278Z.log](https://github.com/user-attachments/files/20599719/a0d7b954_appdaemon_2025-06-04T22-58-44.278Z.log)

```
025-06-04 15:58:38.864010 WARNING HASS: ------------------------------------------------------------
2025-06-04 15:58:39.369394 WARNING HASS: Timed out [0:00:10] waiting for request: {'type': 'get_states', 'id': 5}
2025-06-04 15:58:39.370522 INFO HASS: Completed initialization in 4.9s
2025-06-04 15:58:39.396524 INFO AppDaemon: Processing restart for plugin namespace 'default'
2025-06-04 15:58:39.500474 INFO HASS: Connected to Home Assistant 2025.5.3 with aiohttp websocket
2025-06-04 15:58:39.501785 INFO HASS: Authenticated to Home Assistant 2025.5.3
2025-06-04 15:58:39.506380 INFO HASS: Waiting for Home Assistant to start
2025-06-04 15:58:39.564439 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2025-06-04 15:58:39.586996 INFO AppDaemon: Stopping apps from namespace 'default' because the plugin failed
2025-06-04 15:58:39.775598 WARNING HASS: ------------------------------------------------------------
2025-06-04 15:58:39.776126 WARNING HASS: Unexpected error during websocket send
2025-06-04 15:58:39.776463 WARNING HASS: ------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/appdaemon/utils.py", line 483, in wrapper
    result = await func(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/appdaemon/plugins/hass/hassplugin.py", line 369, in websocket_send_json
    await self.ws.send_json(request)
  File "/usr/lib/python3.12/site-packages/aiohttp/client_ws.py", line 261, in send_json
    await self.send_str(dumps(data), compress=compress)
  File "/usr/lib/python3.12/site-packages/aiohttp/client_ws.py", line 245, in send_str
    await self._writer.send_frame(
  File "/usr/lib/python3.12/site-packages/aiohttp/_websocket/writer.py", line 73, in send_frame
    raise ClientConnectionResetError("Cannot write to closing transport")
aiohttp.client_exceptions.ClientConnectionResetError: Cannot write to closing transport
```
