### ISSUE TITLE
run_daily shift in time

### ISSUE THREAD

**Issue by FrancescoMondada** [hassio-addons/app-appdaemon#428]
I have a script that worked until the last update one week ago.

in appdaemon.yaml
-----
```
appdaemon:
  latitude: XXXX
  longitude: XXXXX
  elevation: 2
  time_zone: Europe/Amsterdam
  plugins:
    HASS:
      type: hass
      ha_url: "http://homeassistant.local:8123"
      # The internal Supervisor URL for Home Assistant’s core API:
      token: "my token"
http:
  url: http://0.0.0.0:5050
admin:
api:
hadashboard:

```
-----

in my code: 
-----
```
B_PROGRAM_OFF       = time(17, 00, 0)
B_PROGRAM_ON        = time(22, 00, 0)

```
.....
in initialize(self)
```
            self.run_daily(self._program_b_off, B_PROGRAM_OFF)
            self.run_daily(self._program_b_on,  B_PROGRAM_ON)

```
.....

definition of functions:

```
    def _program_b_off(self, kwargs):
        """Turn OFF all B-program heaters at 17:00 each day."""
        ts = datetime.now().isoformat()

```
....
```
        self.log(f"{ts} [B-OFF]: Turned OFF B heaters → {turned_off}")
```
----
In my LOG:

```
2025-06-27 18:42:00.611986 INFO SolarHeaterController: 2025-06-27T18:42:00.005007 [B-OFF]: Turned OFF B heaters XXXXXX
```

This action programmed for 17:00 is executed at 18:42:00....

All other actions are delayed of 1:42 . I have reset the system (restating the module) at several hours (in the morning, before the actions firing) but I always have a delay of self.run_daily actions f 1:42. The time zone is the right one (and in any case a wrong time zone would not make such a shift). Any change in the last update (or two updates, they came quickly one after the other) that could explain this?

**Comment by blachner** [comment]
I can confirm that behavior. After my functions also ran with a time delay of 1:42h, I wrote the following test script:

```
import appdaemon.plugins.hass.hassapi as hass
import datetime

class TestTiming(hass.Hass):

    def initialize(self):
        now = datetime.datetime.now()
        self.log(f"Init: current time is {now.strftime('%Y-%m-%d %H:%M:%S')}")

        time_str = self.args.get("time", "12:00:00")
        try:
            target_time = datetime.datetime.strptime(time_str, "%H:%M:%S").time()
        except ValueError:
            self.error(f"Invalid time format '{time_str}', expected HH:MM:SS")
            return

        # Register run_daily
        self.run_daily(self.daily_callback, target_time)
        self.log(f"Registered run_daily at {target_time}")

        # Register run_at (next occurrence of today's time or tomorrow)
        now = datetime.datetime.now()
        run_at_time = now.replace(hour=target_time.hour, minute=target_time.minute, second=target_time.second, microsecond=0)
        if run_at_time <= now:
            run_at_time += datetime.timedelta(days=1)

        self.run_at(self.at_callback, run_at_time)
        self.log(f"Registered run_at at {run_at_time.strftime('%Y-%m-%d %H:%M:%S')}")

    def daily_callback(self, kwargs):
        self.log("run_daily triggered")

    def at_callback(self, kwargs):
        self.log("run_at triggered")
```

```
test_timing:
  module: test_timing
  class: TestTiming
  time: "11:04:00" 
```

This leads to the following output in the log:

```
2025-06-29 11:02:36.206373 INFO test_timing: Init: current time is 2025-06-29 11:02:36
2025-06-29 11:02:36.208053 INFO test_timing: Registered run_daily at 11:04:00
2025-06-29 11:02:36.209216 INFO test_timing: Registered run_at at 2025-06-29 11:04:00
2025-06-29 11:04:00.004747 INFO test_timing: run_at triggered
2025-06-29 12:46:00.004490 INFO test_timing: run_daily triggered
```


The time in the appdaemon container is correct. Callbacks registered via run_at run at the correct time. But via run_daily they are delayed by 1:42h.
