### ISSUE TITLE
Dialogflow stopped working after the update to 4.0

### ISSUE THREAD

**Issue by bruxy70** [hassio-addons/app-appdaemon#5]
# Problem/Motivation

I have an app to handle dialogflow callbacks. It stopped working after the update. 
I have hass.io with Appdaemon 4 0.1.2 add-on.

## Actual behavior

The dialogflow says that it cannot connect to Home Assistant. In the diagnostics it shows 
```
"webhookStatus": {
    "code": 4,
    "message": "Webhook call failed. Error: DEADLINE_EXCEEDED."
  }
```

In all debug log, it initialize the class, but the api_callback is not called.
Originally, the application class was called Dialogflow, and in the class init I have been registering the endpoint: `self.register_endpoint(self.dialogflow_callback, "dialogflow")`
Reading the documentation, I have renamed the class to `Apiai`, renamed the callback to `api_call` and removed the callback registration in initialize, replaced with `pass`, but it still does not work (the first line in the callback function is `self.log(data, level="INFO")`, but it does not show up.

It used to work before (I did have own code to support response, intent and parameters for API v2, but as part of throubleshooting I also removed that and replaced with what is in the documentation - anyhow, the callback is not even called, so this is not an issue.

I have tried to add the self.register_endpoint back, pointing to api_call, but that does not work either.

## Steps to reproduce

In the dialogflow fulfillment I have registered url:
`https://<my domain>:5050/api/appdaemon/dialogflow`
with `x-ad-access`, that is configured in `appdaemon.yaml` api_key:
```yaml
appdaemon:
  latitude: <redacted>
  longitude: <redacted>
  elevation: <redacted>
  time_zone: Europe/Prague
  api_ssl_certificate: /ssl/fullchain.pem
  api_ssl_key: /ssl/privkey.pem
  api_key: <redacted>
  plugins:
    HASS:
      type: hass
http:
  url: http://127.0.0.1:5050
admin:
api:
```
(I have also tried to changed the url to https, but that did not help.

I have 5050 routed to Home Assistant (it worked before, so that works).

And the application is registered this way:
```yaml
dialogflow:
    module: dialogflow
    class: Apiai
```

## Proposed changes

An eaxample (template) of tested dialogflow application would be nice.
