### ISSUE TITLE
appdaemon not start

### ISSUE THREAD

**Issue by denissanga** [hassio-addons/app-appdaemon#50]
Hi all,

I’m trying to write appdaemon app in hassio but I don’t understand why it not start. It not write any log in /config/logs/appdaemon and not write any file as implemented in the hello.py code. I posted in the following all the file I manipulated asking you help to solve it. (Moreover I use duckdns service to reach hassio from remote, but I don’t know if I had to add it on the appdaemon.yaml file)

/config/appdaemon.yaml:
```
##appdaemon.yaml
secrets: /config/secrets.yaml
logs:
  main_log:
    filename: /config/logs/appdaemon/appdaemon.log
  access_log:
    filename: /config/logs/appdaemon/access.log
  error_log:
    filename: /config/logs/appdaemon/error.log
  diag_log:
    filename: /config/logs/appdaemon/diag.log
appdaemon:
  time_zone: Europe/Rome
  production_mode: false
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: !secret home_elevation
  plugins:
    HASS:
      type: hass
http:
  url: http://127.0.0.1:5050
hadashboard:
admin:
api:

```

/config/appdaemon/apps/apps.yaml:

```
hello_world:
  module: hello
  class: HelloWorld
```

/config/appdaemon/apps/hello.py

```
import hassapi as hass
#
# Hello World App
#
# Args:
#
class HelloWorld(hass.Hass):

  def initialize(self):
     self.log("Hello from AppDaemon")
     self.log("You are now ready to run Apps!")
```

thank you very much
Best regards
